/**
 * @author Tanranran
 * @date 2024/4/19 16:52
 * @description
 */
export default class Permission {
  //https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/app-permission-group-list-0000001871741413
  static readonly CAMERA = "ohos.permission.CAMERA"
  static readonly READ_PASTEBOARD = "ohos.permission.READ_PASTEBOARD"
  //https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/oaid-service-0000001774279734#ZH-CN_TOPIC_0000001857915477__%E8%8E%B7%E5%8F%96oaid%E4%BF%A1%E6%81%AF
  static readonly APP_TRACKING_CONSENT = "ohos.permission.APP_TRACKING_CONSENT"
}
